import os
import json
import re
from flask import Flask, render_template, request, jsonify, session
from dotenv import load_dotenv

# Load environment
load_dotenv()

app = Flask(__name__)
app.secret_key = os.environ.get("FLASK_SECRET_KEY", "smartagent_secret_key_2026")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
IS_OFFICIAL_OPENAI = bool(OPENAI_API_KEY and "your_openai_key" not in OPENAI_API_KEY and len(OPENAI_API_KEY) > 20)

# Try imports
try:
    from g4f.client import Client as FreeClient
    HAS_FREE_CLIENT = True
except Exception:
    HAS_FREE_CLIENT = False

# Try official OpenAI imports if key exists
if IS_OFFICIAL_OPENAI:
    try:
        from langchain_openai import ChatOpenAI
        from langchain.agents import AgentExecutor, create_openai_tools_agent
        from langchain.memory import ConversationSummaryBufferMemory
        from langchain_community.tools import DuckDuckGoSearchRun
        from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
    except Exception:
        IS_OFFICIAL_OPENAI = False

SYSTEM_PROMPT = """તમે એક Expert AI Agent છો — smart, helpful, અને trustworthy.

🗣️ ભાષા: હંમેશા **Desi Gujarati** માં જ communicate કરો. 
   (Technical terms જેમ કે Python, API, file, etc. English માં રાખો.)

⚠️ STRICT RULES — Zero Hallucinations:
1. **File create કરતાં પહેલાં** હંમેશા user ને options આપો:
   "[A] હા, file create કરો  [B] ના, cancel કરો"
   User [A] select કરે ત્યારે જ ફાઇલ ક્રિએટ કરવાની વાત કરો.

2. ક્યારેય API keys અથવા સેન્સિટિવ ડેટા લીક ન કરો.
3. જો ખબર ન હોય, સ્પષ્ટ કહો: "મને ખ્યાલ નથી, search કરીને confirm કરું?"
4. Professional, friendly, અને concise responses આપો.
"""

# Store memory per session
memory_store = {}

def call_free_llm(user_message, session_id):
    """Fallback Free LLM provider using g4f or free endpoints — NO API KEY REQUIRED."""
    history = memory_store.get(session_id, [])
    
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    for h in history[-6:]: # keep last 6 turns
        messages.append(h)
    messages.append({"role": "user", "content": user_message})

    # File creation intent detection
    if "file" in user_message.lower() or "ફાઈલ" in user_message or "કોડ" in user_message or "create" in user_message.lower():
        if "[a]" in user_message.lower() or "હા" in user_message:
            # User confirmed
            os.makedirs("agent_output", exist_ok=True)
            filename = "generated_script.py"
            filepath = os.path.join("agent_output", filename)
            with open(filepath, "w", encoding="utf-8") as f:
                f.write("# Generated by Smart Agent AI\nprint('Hello from Smart Agent Desi Gujarati AI!')\n")
            
            res_text = f"✅ ફાઇલ `{filename}` સફળતાપૂર્વક `agent_output/` ફોલ્ડરમાં બનાવી દીધી છે!"
            history.append({"role": "user", "content": user_message})
            history.append({"role": "assistant", "content": res_text})
            memory_store[session_id] = history
            return res_text

    if HAS_FREE_CLIENT:
        try:
            client = FreeClient()
            response = client.chat.completions.create(
                model="gpt-4o",
                messages=messages
            )
            ans = response.choices[0].message.content
            if ans and len(ans.strip()) > 0:
                history.append({"role": "user", "content": user_message})
                history.append({"role": "assistant", "content": ans})
                memory_store[session_id] = history
                return ans
        except Exception as e:
            pass

    # Basic intelligent fallback if g4f network is limited
    ans = f"નમસ્તે! હું તમારો Smart Agent છું. તમે પૂછ્યું: '{user_message}'. હું તમને ગુજરાતીમાં મદદ કરવા માટે તૈયાર છું! 🚀"
    history.append({"role": "user", "content": user_message})
    history.append({"role": "assistant", "content": ans})
    memory_store[session_id] = history
    return ans


@app.route("/")
def index():
    if "session_id" not in session:
        session["session_id"] = os.urandom(16).hex()
    return render_template("index.html")


@app.route("/chat", methods=["POST"])
def chat():
    data = request.get_json()
    if not data or "message" not in data:
        return jsonify({"error": "Invalid request"}), 400

    user_message = data["message"].strip()
    if not user_message:
        return jsonify({"error": "Empty message"}), 400

    session_id = session.get("session_id", "default")

    # Use Free LLM if official key is absent or placeholder
    try:
        response = call_free_llm(user_message, session_id)
    except Exception as e:
        response = f"❌ Error: {str(e)[:200]}"

    return jsonify({"response": response})


@app.route("/clear", methods=["POST"])
def clear_memory():
    session_id = session.get("session_id", "default")
    if session_id in memory_store:
        del memory_store[session_id]
    return jsonify({"status": "✅ Chat history clear થઈ ગઈ!"})


@app.route("/health")
def health():
    return jsonify({"status": "ok", "mode": "free_gpt4o", "version": "2.0.0"})


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
